- components/ExplainTemporal.js
- components/Footer.js
- next.config.js
- package.json
- yarn.lock
> switch to preact

- components/Footer.js
For when this lands: https://github.com/temporalio/documentation/pull/210
> updating link to docs

- components/TemporalVs.js
- components/UseCases.js
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
* Update to the use cases section
* Update to the TemporalVs section
I updated the two sections to better elaborate on the upsides of using temporal.
Also fixed some minor spelling issues
1. Closes issue: 
> Update to use cases and temporalVs sections

- pages/press.js
> add corporate address

- components/ExplainTemporal.js
- components/Hero.js
- components/JoinUs.js
- styles/index.css
- componentize button styles
- updates swyx bar colors
- remove smooth scroll for vestibular disorders
1. Closes 
> feat: Scrollbar + Button Styles

- components/Hero.js
- Extend `iframe` size for Github button
1. Closes 
> feat: extend stars iframe width

- components/CaseStudies.js
- components/StarCanvas.js
- package-lock.json
- package.json
- pages/_app.js
- styles/index.css
- Fix `overflow` on body
- Sort out case studies jumping by putting logos at top and leaving the see more at the bottom. I think this feels better than both controls at the top.
- Implemented randomly generated star canvas that reacts to cursor movement
- Optional Easter Egg that I can remove. Type "temporal" and the stars will go into "Party" mode 🎉 
- We could ditch the SVG for the backdrop now, that's a ~200kb file that we don't need if we're going to use canvas and a little JavaScript 😉 
1. Closes 
> feat: StarCanvas

- codesamples/sample.go
- codesamples/sample.java
- codesamples/sample.js
- codesamples/sample.php
continued iteration on code samples. followup from #35 
we abandoned signals in https://gist.github.com/sw-yx/4b8d660635ede59d8870b17b6b4e9e95 - we would like to bring it back in some way.
> landing page code Samples v2

- pages/careers.js
- vercel.json
add Descript job and force rebuild
was getting opaque failure from main
> add Descript job and force rebuild

- components/ExplainTemporal.js
- I was using a video from the `/public` folder. Switched to embed because there was an audio issue + to log views
- Also updated the button design
> Use YouTube embed for video and update button design

- components/Banner.js
- components/Hero.js
- components/Nav.js
- components/StackedUseCases.js
- components/StarCanvas.js
- pages/careers.js
- pages/index.js
- pages/usecases.js
- styles/index.css
Fixes up a few assorted accessibility issues. Attempts to keep the pages generally visually the same as they were before, except where noted (mostly for color contrast reasons).
Explanations & any visual changes marked inline.
Accessibility! 🦾💖 
1. Closes #55 
I checked screen resolutions on example mobile (400px), tablet (800px), and desktop (1600px) widths.
> Accessibility touchups

- components/FAQ.js
> add spacing

- components/layout/Banner.js
The banner close button wasn't properly aligned
Before:
After:
> fix banner close button

- components/TemporalSDKs/TemporalSDKs.js
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>
1. Closes 
> Update title of Temporal SDKs section

- pages/_app.js
> Announcement commit

- pages/_app.js
> Add analytics

- components/LogoList.js
> Fix Logo's

- components/CodeSnippets.js
> Fix code samples

- components/Count.js
- pages/_app.js
- pages/home/index.js
- tailwind.config.js
> Count up and use proper Font.

- components/Count.js
> Another round of counting

- pages/careers/index.js
> Drop console.log
